version: '2'

services:
  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_HOST=172.17.0.1
      - ADVERTISED_PORT=9092
    ports:
      - "2181:2181"
      - "9092:9092"

  minio:
    image: minio/minio
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/export
      - minio-config:/root/.minio
    entrypoint: >
      /bin/sh -c "
      curl https://raw.githubusercontent.com/harshavardhana/minio-kafka/master/wait-for.sh -o wait-for.sh;
      [ ! -f /root/.minio/config.json ] && curl https://raw.githubusercontent.com/harshavardhana/minio-kafka/master/config.json -o /root/.minio/config.json;
      chmod +x wait-for.sh;
      ./wait-for.sh kafka:9092 -- /usr/bin/docker-entrypoint.sh minio server /export;
      "

volumes:
  minio-data:
  minio-config:
